"""
Unit tests for the `textfsmgen.engine.tabular.VarColumnTabularTranslator` class.

Usage
-----
Run pytest in the project root to execute these tests:
    $ pytest tests/unit/engine/tabular/test_to_template.py
    or
    $ python -m pytest tests/unit/engine/tabular/test_to_template.py
"""


import re

from textwrap import dedent

from textfsmgen.engine.tabular import VarColumnTabularTranslator

from textfsmgen.core.verify import verify
from textfsmgen.core.template import get_textfsm_template


def test_ex1():
    test_data = dedent("""
        LastWriteTime          Name
        9/1/2021 6:13:50 AM    reference
        10/5/2021 9:13:50 PM   dsc
        11/2/2021 11:58:45 PM  README.md
        12/16/2021 12:30:59 PM CONTRIBUTING.md
    """).strip()

    expected_template_snippet = dedent("""
        LastWriteTime          Name
        start() 3_mixed_word(var_lastwritetime)  mixed_word(var_name) end() -> record
    """).strip()

    expected_template = dedent(r"""
        ################################################################################
        # Template is generated by TextFSMGen CE
        # Created date: YYYY-mm-dd
        ################################################################################
        Value lastwritetime ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*(\s+[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*){2})
        Value name ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)
        
        Start
          ^LastWriteTime +Name
          ^${lastwritetime} +${name}$$ -> Record
    """).strip()

    expected_result = [
        {'lastwritetime': '9/1/2021 6:13:50 AM', 'name': 'reference'},
        {'lastwritetime': '10/5/2021 9:13:50 PM', 'name': 'dsc'},
        {'lastwritetime': '11/2/2021 11:58:45 PM', 'name': 'README.md'},
        {'lastwritetime': '12/16/2021 12:30:59 PM', 'name': 'CONTRIBUTING.md'}
    ]

    node = VarColumnTabularTranslator(
        test_data, column_divider='  ', column_count=2,
        header_rows='LastWriteTime          Name'
    )
    tmpl_snippet = node.to_template_snippet()
    assert tmpl_snippet == expected_template_snippet

    template = get_textfsm_template(tmpl_snippet)
    template = re.sub(r'date: \d{4}-\d\d-\d\d', 'date: YYYY-mm-dd', template)
    assert template == expected_template

    is_verified = verify(tmpl_snippet, test_data, expected_result=expected_result)
    assert is_verified


def test_ex2():
    test_data = dedent("""
        fruits    meat      drinks
        ------    --------  -------
        orange    pork      water
        peach               pepsi soda
        mango     chicken
    """).strip()

    expected_template_snippet = dedent("""
        fruits    meat      drinks
        start() word(var_fruits)  word(var_meat)  words(var_drinks) end() -> record
        start() word(var_fruits)  word(var_meat) end(space) -> record
        start() word(var_fruits) 10_15_space() words(var_drinks) end() -> record
    """).strip()

    expected_template = dedent(r"""
        ################################################################################
        # Template is generated by TextFSMGen CE
        # Created date: YYYY-mm-dd
        ################################################################################
        Value fruits ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)
        Value meat ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)
        Value drinks ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*(\s+[a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)*)
        
        Start
          ^fruits +meat +drinks
          ^${fruits} +${meat} +${drinks}$$ -> Record
          ^${fruits} +${meat} *$$ -> Record
          ^${fruits}  {10,15} ${drinks}$$ -> Record
    """).strip()

    expected_result = [
        {'fruits': 'orange', 'meat': 'pork', 'drinks': 'water'},
        {'fruits': 'peach', 'meat': 'pepsi', 'drinks': 'soda'},
        {'fruits': 'mango', 'meat': 'chicken', 'drinks': ''}
    ]

    node = VarColumnTabularTranslator(test_data)
    tmpl_snippet = node.to_template_snippet()
    assert tmpl_snippet == expected_template_snippet

    template = get_textfsm_template(tmpl_snippet)
    template = re.sub(r'date: \d{4}-\d\d-\d\d', 'date: YYYY-mm-dd', template)
    assert template == expected_template

    is_verified = verify(tmpl_snippet, test_data, expected_result=expected_result)
    assert is_verified
