"""
Unit tests for the `textfsmgen.core.TemplateBuilder.create_python_test` method.

Usage
-----
Run pytest in the project root to execute these tests:
    $ pytest tests/unit/auto_generate_test_script/test_generating_python_script.py
    or
    $ python -m pytest tests/unit/auto_generate_test_script/test_generating_python_script.py
"""

from datetime import datetime
from textfsmgen import TemplateBuilder

from textfsmgen.libs.common import dedent_and_strip


class TestTemplateBuilderPythonScript:
    def test_creating_python_script(self):
        test_data = dedent_and_strip("""
            Title                   Price       Genre
            XML Developer's Guide   44.95       Computer
            Midnight Rain           5.95        Fantasy
            Maeve Ascendant         5.95        Fantasy
        """)

        user_data = dedent_and_strip("""
            Title                   Price       Genre
            mixed_words(var_title)   number(var_price)   words(var_genre) -> Record
        """)

        expected_script = dedent_and_strip(r'''
            """Python snippet script is generated by TextFSM Generator Community Edition"""

            from textfsm import TextFSM
            from io import StringIO

            template = r"""################################################################################
            # Template is generated by TextFSM Generator Community Edition
            # Created date: _datetime_
            ################################################################################
            Value title ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)*)
            Value price (\d*[.]?\d+)
            Value genre ([a-zA-Z][a-zA-Z0-9]*( [a-zA-Z][a-zA-Z0-9]*)*)

            Start
              ^Title +Price +Genre
              ^${title} +${price} +${genre} -> Record"""

            test_data = """Title                   Price       Genre
            XML Developer's Guide   44.95       Computer
            Midnight Rain           5.95        Fantasy
            Maeve Ascendant         5.95        Fantasy"""


            def test_textfsm_template(template_, test_data_):
                """test textfsm template via test data

                Parameters
                ----------
                template_ (str): a content of textfsm template.
                test_data_ (str): test data.
                """

                # show test data
                print("Test data:\n----------\n%s" % test_data_)
                print("\n%s\n" % ("+" * 40))

                # show textfsm template
                print("Template:\n---------\n%s" % template_)

                stream = StringIO(template_)
                parser = TextFSM(stream)
                rows = parser.ParseTextToDicts(test_data_)
                total_rows_count = len(rows)
                assert total_rows_count > 0

                # print parsed result
                print("\n%s\n" % ("+" * 40))
                print("Result:\n-------\n%s\n" % rows)

            # function call
            test_textfsm_template(template, test_data)
        ''')

        dt_str = format(datetime.now(), '%Y-%m-%d')
        expected_script = expected_script.replace('_datetime_', dt_str)

        factory = TemplateBuilder(user_data=user_data, test_data=test_data)
        pytest_script = factory.create_python_test()
        assert pytest_script == expected_script
