[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "textfsmgen"
version = "0.7.0"
description = "TextFSM Generator transforms plain‑English snippets into production‑ready TextFSM templates using a low‑code, no‑code workflow and built‑in Golden Master Testing, empowering both professional and citizen developers to create reliable, reusable parsing logic."
readme = "README.md"
readme-content-type = "text/markdown"
license = "BSD-3-Clause"
requires-python = ">=3.9"

authors = [
  { name = "Tuyen Mathew Duong", email = "tuyen@geekstrident.com" }
]

maintainers = [
  { name = "Tuyen Mathew Duong", email = "tuyen@geekstrident.com" }
]

dependencies = [
  "textfsm>=1.1.0",
  "pyyaml>=6.0",
]

keywords = [
  "low-code", "no-code", "citizen developer",
  "automation", "workflow automation", "process automation",
  "textfsm", "textfsm generator", "text parsing",
  "verification", "validation", "qa", "test automation",
  "robotframework", "test script",
  "ai integration", "ai-assisted automation", "generative ai"
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Natural Language :: English",
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Intended Audience :: End Users/Desktop",
  "Intended Audience :: Information Technology",
  "Intended Audience :: Manufacturing",
  "Intended Audience :: Other Audience",
  "Intended Audience :: Science/Research",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: POSIX :: Linux",
  "Operating System :: Microsoft :: Windows",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Code Generators",
  "Topic :: Software Development :: Quality Assurance",
  "Topic :: Software Development :: Testing",
  "Topic :: Scientific/Engineering",
  "Topic :: Text Processing",
]

[project.urls]
Documentation = "https://geeks-trident-llc.github.io/textfsmgen/"
# Documentation = "https://github.com/Geeks-Trident-LLC/textfsmgen/wiki"
Repository = "https://github.com/Geeks-Trident-LLC/textfsmgen"
Issues = "https://github.com/Geeks-Trident-LLC/textfsmgen/issues"

[project.scripts]
# textfsmgen = "textfsmgen.main:execute"
# textfsmgen = "textfsmgen.cli:main"
# textfsmgen = "textfsmgen.cli:main"
textfsmgen-golden = "textfsmgen.cli.golden.cli:cli"
textfsmgen-gt = "textfsmgen.cli.golden.cli:cli"
textfsmgen = "textfsmgen.cli.top:cli"
textfsmgen-gui = "textfsmgen.application:execute"
textfsmgen-app = "textfsmgen.application:execute"
textfsm-app = "textfsmgen.application:execute"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
exclude = [
  "tests*", "testing*", "examples*",
  "build*", "dist*", "docs*", "venv*"
]

[tool.setuptools.package-data]
"*" = ["LICENSE", "README.md"]

[tool.ruff]
src = ["textfsmgen", "tests"]
extend-exclude = ["tests/golden",]
