[tox]
envlist = py{39,310,311,312,313,314}, lint
skip_missing_interpreters = true

[testenv]
deps = -r requirements-dev.txt
commands =
    python scripts/check_generic_imports.py
    pytest \
        --cov=textfsmgen \
        --cov-report=term-missing \
        --cov-report=html \
        --cov-fail-under=30 \
        -sv {posargs:tests}

[testenv:lint]
basepython = python3.12
deps = ruff
commands =
    ruff check textfsmgen tests --fix
    ruff format textfsmgen tests
