"""
Integration tests for the `textfsmgen.core.TemplateBuilder.create_pytest` method.

Usage
-----
Run pytest in the project root to execute these tests:
    $ pytest tests/integration/generate_test_script/test_pytest_script.py
    or
    $ python -m pytest tests/integration/generate_test_script/test_pytest_script.py
"""

from datetime import datetime
from textfsmgen import TemplateBuilder

from textfsmgen.libs.common import dedent_and_strip


def test():
    test_data = dedent_and_strip("""
        Title                   Price       Genre
        XML Developer's Guide   44.95       Computer
        Midnight Rain           5.95        Fantasy
        Maeve Ascendant         5.95        Fantasy
    """)

    user_data = dedent_and_strip("""
        Title                   Price       Genre
        mixed_words(var_title)   number(var_price)   words(var_genre) -> Record
    """)

    expected_script = dedent_and_strip(r'''
        """Python pytest script is generated by TextFSMGen CE"""
        
        from textfsm import TextFSM
        from io import StringIO
        
        template = r"""################################################################################
        # Template is generated by TextFSMGen CE
        # Created date: _datetime_
        ################################################################################
        Value title ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*(\s+[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)*)
        Value price (\d*[.]?\d+)
        Value genre ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*(\s+[a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)*)
        
        Start
          ^Title +Price +Genre
          ^${title} +${price} +${genre} -> Record"""
        
        test_data = """Title                   Price       Genre
        XML Developer's Guide   44.95       Computer
        Midnight Rain           5.95        Fantasy
        Maeve Ascendant         5.95        Fantasy"""
        
        
        class TestTemplate:
            def test_textfsm_template(self):
                stream = StringIO(template)
                parser = TextFSM(stream)
                rows = parser.ParseTextToDicts(test_data)
                total_rows_count = len(rows)
                assert total_rows_count > 0
        
        if __name__ == "__main__":
            import pytest
            raise SystemExit(pytest.main(["-v", __file__]))
    ''')

    dt_str = format(datetime.now(), "%Y-%m-%d")
    expected_script = expected_script.replace("_datetime_", dt_str)

    factory = TemplateBuilder(user_data=user_data, test_data=test_data)
    pytest_script = factory.create_pytest()
    assert pytest_script == expected_script
