"""
Unit tests for the `textfsmgen.core` module.

Usage
-----
Run pytest in the project root to execute these tests:
    $ pytest tests/unit/core
    or
    $ python -m pytest tests/unit/core
"""

from datetime import datetime
from textfsmgen.libs.common import dedent_and_strip


def get_user_data(case="case1"):
    """
    Returns sample user data snippets for template generation.
    Case 1: Basic table with Title, Price, Genre.
    Case 2: Extended table with comments and keep markers.
    Defaults to "case1" if no case is specified.
    """
    if case == "case1":
        user_data = dedent_and_strip("""
            Title                   Price       Genre
            mixed_words(var_title)   number(var_price)   words(var_genre) -> Record
        """)
        return user_data
    elif case == "case2":
        user_data = dedent_and_strip("""
            comment__ Title column consists a list of mixed words
            comment__ Price column is number.  It can be digits or float number
            comment__ Genre column is a group of words
            Title                   Price       Genre
            keep__ =+ +=+ +=+
            mixed_words(var_title)   number(var_price)   words(var_genre) -> Record
        """)
        return user_data
    else:
        return "NO-USER-DATA"


def get_expected_template(case="case1"):
    """
    Returns the expected TextFSM template string for the given case.
    The template includes metadata headers, variable definitions,
    and parsing rules. The creation date is dynamically inserted.
    """
    dt_str = datetime.now().strftime("%Y-%m-%d")
    if case == "case1":
        template = dedent_and_strip("""
            ################################################################################
            # Template is generated by TextFSMGen CE
            # Created date: _datetime_
            ################################################################################
            Value title ([\\x21-\\x7e]*[a-zA-Z0-9][\\x21-\\x7e]*(\\s+[\\x21-\\x7e]*[a-zA-Z0-9][\\x21-\\x7e]*)*)
            Value price (\\d*[.]?\\d+)
            Value genre ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*(\\s+[a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)*)

            Start
              ^Title +Price +Genre
              ^${title} +${price} +${genre} -> Record
        """)
        template = template.replace('_datetime_', dt_str)
        return template
    elif case == "case2":
        template = dedent_and_strip("""
            ################################################################################
            # Template is generated by TextFSMGen CE
            # Created date: _datetime_
            ################################################################################
            Value title ([\\x21-\\x7e]*[a-zA-Z0-9][\\x21-\\x7e]*(\\s+[\\x21-\\x7e]*[a-zA-Z0-9][\\x21-\\x7e]*)*)
            Value price (\\d*[.]?\\d+)
            Value genre ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*(\\s+[a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)*)

            Start
              # Title column consists a list of mixed words
              # Price column is number.  It can be digits or float number
              # Genre column is a group of words
              ^Title +Price +Genre
              ^=+ +=+ +=+
              ^${title} +${price} +${genre} -> Record
        """)
        template = template.replace('_datetime_', dt_str)
        return template
    else:
        return "NO-TEMPLATE"


def get_test_data():
    """
    Provides sample tabular input data (Title, Price, Genre) to be
    parsed by the generated TextFSM template.
    """
    test_data = dedent_and_strip("""
        Title                   Price       Genre
        XML Developer's Guide   44.95       Computer
        Midnight Rain           5.95        Fantasy
        Maeve Ascendant         5.95        Fantasy
    """)
    return test_data


def get_expected_result():
    """
    Returns the expected parsed output as a list of dictionaries,
    mapping Title, Price, and Genre values from the test data.
    """
    expected_result = [
        dict(title="XML Developer's Guide", price="44.95", genre="Computer"),
        dict(title="Midnight Rain", price="5.95", genre="Fantasy"),
        dict(title="Maeve Ascendant", price="5.95", genre="Fantasy"),
    ]
    return expected_result