"""
Unit tests for the `textfsmgen.engine.doc` module.

Usage
-----
Run pytest in the project root to execute these tests:
    $ pytest tests/integration/snippet_explanation_doc
    or
    $ python -m pytest tests/integration/snippet_explanation_doc
"""


def get_keywords(category: str = "singular"):
    """Return the list of keyword names for the given category."""
    keywords = {
        "singular": [
            "dot",
            "space",
            "ws",
            "whitespace",
            "digit",
            "letter",
            "alnum",
            "punct",
            "punctuation",
            "graph",
            "non_ws",
            "non_whitespace",
            "sop",
            "pos",
            "space_or_punct",
            "punct_or_space",
            "lop",
            "pol",
            "letter_or_punct",
            "punct_or_letter",
        ],
        "plural": [
            "dots",
            "spaces",
            "wss",
            "whitespaces",
            "digits",
            "letters",
            "alnums",
            "puncts",
            "punctuations",
            "graphs",
            "non_wss",
            "non_whitespaces",
            "sops",
            "poss",
            "spaces_or_puncts",
            "puncts_or_spaces",
            "lops",
            "pols",
            "letters_or_puncts",
            "puncts_or_letters",
        ],
        "semantic": [
            "word",
            "mixed_word",
            "number",
            "mixed_number",
        ],
        "plural_semantic": [
            "words",
            "mixed_words",
            "numbers",
            "mixed_numbers",
        ],
        "group": [
            "dot_group",
            "space_group",
            "ws_group",
            "whitespace_group",
            "digit_group",
            "letter_group",
            "alnum_group",
            "punct_group",
            "punctuation_group",
            "graph_group",
            "non_ws_group",
            "non_whitespace_group",
            "space_or_punct_group",
            "punct_or_space_group",
            "sop_group",
            "pos_group",
            "letter_or_punct_group",
            "punct_or_letter_group",
            "lop_group",
            "pol_group",
            "dots_group",
            "spaces_group",
            "wss_group",
            "whitespaces_group",
            "digits_group",
            "letters_group",
            "alnums_group",
            "puncts_group",
            "punctuations_group",
            "graphs_group",
            "non_wss_group",
            "non_whitespaces_group",
            "spaces_or_puncts_group",
            "puncts_or_spaces_group",
            "sops_group",
            "poss_group",
            "letters_or_puncts_group",
            "puncts_or_letters_group",
            "lops_group",
            "pols_group",
            "word_group",
            "mixed_word_group",
            "number_group",
            "mixed_number_group",
            "words_group",
            "mixed_words_group",
            "numbers_group",
            "mixed_numbers_group",
        ],
    }

    return keywords.get(category, [])
