"""
Unit tests for the `textfsmgen.gpcategory.CategoryLinePattern` class.

Usage
-----
Run pytest in the project root to execute these tests:
    $ pytest tests/unit/gpcategory/test_category_line_pattern_class.py
    or
    $ python -m pytest tests/unit/gpcategory/test_category_line_pattern_class.py
"""


import re

import pytest

from textfsmgen.verify import verify
from textfsmgen.core import get_textfsm_template

from textfsmgen.gpcategory import CategoryLinePattern

from tests.unit import replace_dates_with_placeholder

from textfsmgen.deps import genericlib_dedent_and_strip as dedent_and_strip


class TestCategoryLinePattern:
    """Test class for CategoryLinePattern"""
    @pytest.mark.parametrize(
        "line, count, expected_pattern, expected_result",
        [
            (
                'fruits: orange, peach',
                1,
                r'fruits: *(?P<fruits>[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)',  # noqa
                {'fruits': 'orange, peach'}
            ),
            (
                'total   fruits: orange, peach',
                1,
                r'total +fruits: *(?P<total_fruits>[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)',     # noqa
                {'total_fruits': 'orange, peach'}
            ),
            (
                'total fruit(s): orange, peach',
                1,
                r'total fruit\(s\): *(?P<total_fruit_s>[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)',   # noqa
                {'total_fruit_s': 'orange, peach'}
            ),
            (
                'fruits: orange   meat: pork  drinks: water',
                3,
                r'fruits: *(?P<fruits>[a-zA-Z]+) +meat: *(?P<meat>[a-zA-Z]+) +drinks: *(?P<drinks>[a-zA-Z]+)',
                {'fruits': 'orange', 'meat': 'pork', 'drinks': 'water'}
            ),
            (
                'fruits:   meat: ',
                2,
                r'fruits: *(?P<fruits>.*|) +meat: *(?P<meat>.*|)',
                {'fruits': '', 'meat': ''}
            ),
            (
                'fruits:   meat:  drinks: ',
                3,
                r'fruits: *(?P<fruits>.*|) +meat: *(?P<meat>.*|) +drinks: *(?P<drinks>.*|)',
                {'fruits': '', 'meat': '', 'drinks': ''}
            ),
            (
                'fruits:   meat: pork  drinks: ',
                3,
                r'fruits: *(?P<fruits>.*|) +meat: *(?P<meat>[a-zA-Z]+) +drinks: *(?P<drinks>.*|)',
                {'fruits': '', 'meat': 'pork', 'drinks': ''}
            ),
            (
                'fruits:   meat: pork  drinks: water',
                3,
                r'fruits: *(?P<fruits>.*|) +meat: *(?P<meat>[a-zA-Z]+) +drinks: *(?P<drinks>[a-zA-Z]+)',
                {'fruits': '', 'meat': 'pork', 'drinks': 'water'}
            ),
            (
                'fruits: orange, peach  meat:   drinks: water',
                3,
                r'fruits: *(?P<fruits>[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+) +meat: *(?P<meat>.*|) +drinks: *(?P<drinks>[a-zA-Z]+)',    # noqa
                {'fruits': 'orange, peach', 'meat': '', 'drinks': 'water'}
            ),
            (
                'time: 08:30:00 P.M.',
                1,
                r'time: *(?P<time>[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)',
                {'time': '08:30:00 P.M.'}
            ),
            (
                'time: 08:30:00 P.M.  mac_addr: 11:22:33:44:55:66',
                2,
                r'time: *(?P<time>[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+) +mac_addr: *(?P<mac_addr>[+\(\[\$-]?(\d+([,:/-]\d+)*)?[.]?\d+[\]\)%a-zA-Z]*)',     # noqa
                {'time': '08:30:00 P.M.', 'mac_addr': '11:22:33:44:55:66'}
            ),
            (
                'time: 08:30:00 P.M.   ipv6: ::1234, 2000::ab, 2000::   mac_addr: 11:22:33:44:55:66',
                3,
                r'time: *(?P<time>[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+) +ipv6: *(?P<ipv6>[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+) +mac_addr: *(?P<mac_addr>[+\(\[\$-]?(\d+([,:/-]\d+)*)?[.]?\d+[\]\)%a-zA-Z]*)',   # noqa
                {'time': '08:30:00 P.M.', 'ipv6': '::1234, 2000::ab, 2000::', 'mac_addr': '11:22:33:44:55:66'}
            ),
        ]
    )
    def test_to_regex(self, line: str, count: int, expected_pattern: str,
                      expected_result: dict) -> None:
        """
        Verify that `CategoryLinePattern.to_regex` generates the expected regex
        pattern and correctly matches the provided line.

        Parameters
        ----------
        line : str
            Input line of text to be parsed.
        count : int
            Count argument passed to `CategoryLinePattern`.
        expected_pattern : str
            The expected regex pattern generated by `to_regex`.
        expected_result : dict
            The expected dictionary of captured groups from the regex match.
        """
        # --- Action ---
        node = CategoryLinePattern(line, count=count)
        pattern = node.to_regex()

        # --- Assertions ---
        assert pattern == expected_pattern, (
            f"Generated pattern {pattern!r} does not match expected {expected_pattern!r}"
        )

        match = re.match(pattern, line)
        if not match:
            pytest.fail(
                f"No match found for line {line!r} using pattern {pattern!r}")

        result = match.groupdict()
        assert result == expected_result, (
            f"Regex groups {result} do not match expected {expected_result}"
        )

    @pytest.mark.parametrize(
        "line, count, expected_template_snippet, expected_textfsm_template, expected_result",
        [
            (
                'fruits:  orange, peach',
                1,
                r'fruits:  mixed_phrase(var_fruits)',
                dedent_and_strip(r"""
                    ################################################################################
                    # Template is generated by TextFSM Generator Community Edition
                    # Created date: YYYY-mm-dd
                    ################################################################################
                    Value fruits ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)

                    Start
                      ^fruits: +${fruits}
                """),
                [{'fruits': 'orange, peach'}]
            ),
            (
                'total fruit(s): orange, peach',
                1,
                r'total fruit(s): mixed_phrase(var_total_fruit_s)',
                dedent_and_strip(r"""
                    ################################################################################
                    # Template is generated by TextFSM Generator Community Edition
                    # Created date: YYYY-mm-dd
                    ################################################################################
                    Value total_fruit_s ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)

                    Start
                      ^total fruit\(s\): ${total_fruit_s}
                """),
                [{'total_fruit_s': 'orange, peach'}]
            ),
            (
                '  fruit(s): orange   meat: pork  drinks: water',
                3,
                r'  fruit(s): letters(var_fruit_s)  meat: letters(var_meat)  drinks: letters(var_drinks)',
                dedent_and_strip(r"""
                    ################################################################################
                    # Template is generated by TextFSM Generator Community Edition
                    # Created date: YYYY-mm-dd
                    ################################################################################
                    Value fruit_s ([a-zA-Z]+)
                    Value meat ([a-zA-Z]+)
                    Value drinks ([a-zA-Z]+)

                    Start
                      ^ +fruit\(s\): ${fruit_s} +meat: ${meat} +drinks: ${drinks}
                """),
                [{'fruit_s': 'orange', 'meat': 'pork', 'drinks': 'water'}]
            ),
            (
                'fruits:   meat: ',
                2,
                r'fruits:zero_or_spaces()something(var_fruits, or_empty)  meat:zero_or_spaces()something(var_meat, or_empty)',  # noqa
                dedent_and_strip(r"""
                    ################################################################################
                    # Template is generated by TextFSM Generator Community Edition
                    # Created date: YYYY-mm-dd
                    ################################################################################
                    Value fruits ((.*|))
                    Value meat ((.*|))

                    Start
                      ^fruits: *${fruits} +meat: *${meat}
                """),
                [{'fruits': '', 'meat': ''}]
            ),
            (
                'fruits: orange   meat:  drinks: water',
                3,
                r'fruits: letters(var_fruits)  meat:zero_or_spaces()something(var_meat, or_empty)  drinks: letters(var_drinks)',    # noqa
                dedent_and_strip(r"""
                    ################################################################################
                    # Template is generated by TextFSM Generator Community Edition
                    # Created date: YYYY-mm-dd
                    ################################################################################
                    Value fruits ([a-zA-Z]+)
                    Value meat ((.*|))
                    Value drinks ([a-zA-Z]+)

                    Start
                      ^fruits: ${fruits} +meat: *${meat} +drinks: ${drinks}
                """),
                [{'fruits': 'orange', 'meat': '', 'drinks': 'water'}]
            ),
            (
                'fruits:   meat:  drinks: water',
                3,
                r'fruits:zero_or_spaces()something(var_fruits, or_empty)  meat:zero_or_spaces()something(var_meat, or_empty)  drinks: letters(var_drinks)',     # noqa
                dedent_and_strip(r"""
                    ################################################################################
                    # Template is generated by TextFSM Generator Community Edition
                    # Created date: YYYY-mm-dd
                    ################################################################################
                    Value fruits ((.*|))
                    Value meat ((.*|))
                    Value drinks ([a-zA-Z]+)

                    Start
                      ^fruits: *${fruits} +meat: *${meat} +drinks: ${drinks}
                """),
                [{'fruits': '', 'meat': '', 'drinks': 'water'}]
            ),
            (
                'time: 08:30:00 P.M.',
                1,
                r'time: mixed_phrase(var_time)',
                dedent_and_strip(r"""
                    ################################################################################
                    # Template is generated by TextFSM Generator Community Edition
                    # Created date: YYYY-mm-dd
                    ################################################################################
                    Value time ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)

                    Start
                      ^time: ${time}
                """),
                [{'time': '08:30:00 P.M.'}]
            ),
            (
                'time: 08:30:00 P.M.   mac_addr: 11:22:33:44:55:66',
                2,
                r'time: mixed_phrase(var_time)  mac_addr: mixed_number(var_mac_addr)',
                dedent_and_strip(r"""
                    ################################################################################
                    # Template is generated by TextFSM Generator Community Edition
                    # Created date: YYYY-mm-dd
                    ################################################################################
                    Value time ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)
                    Value mac_addr ([+\(\[\$-]?(\d+([,:/-]\d+)*)?[.]?\d+[\]\)%a-zA-Z]*)

                    Start
                      ^time: ${time} +mac_addr: ${mac_addr}
                """),
                [{'time': '08:30:00 P.M.', 'mac_addr': '11:22:33:44:55:66'}]
            ),
            (
                'time: 08:30:00 P.M.   ipv6: ::1234, 2000::ab, 2000::   mac_addr: 11:22:33:44:55:66',
                3,
                r'time: mixed_phrase(var_time)  ipv6: mixed_phrase(var_ipv6)  mac_addr: mixed_number(var_mac_addr)',
                dedent_and_strip(r"""
                    ################################################################################
                    # Template is generated by TextFSM Generator Community Edition
                    # Created date: YYYY-mm-dd
                    ################################################################################
                    Value time ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)
                    Value ipv6 ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)
                    Value mac_addr ([+\(\[\$-]?(\d+([,:/-]\d+)*)?[.]?\d+[\]\)%a-zA-Z]*)
                    
                    Start
                      ^time: ${time} +ipv6: ${ipv6} +mac_addr: ${mac_addr}
                """),
                [{'time': '08:30:00 P.M.', 'ipv6': '::1234, 2000::ab, 2000::', 'mac_addr': '11:22:33:44:55:66'}]
            ),
        ]
    )
    def test_to_template_snippet(
            self,
            line: str,
            count: int,
            expected_template_snippet: str,
            expected_textfsm_template: str,
            expected_result: list[dict],
    ) -> None:
        """
        Verify that `CategoryLinePattern.to_template_snippet` generates the expected
        snippet, produces a valid TextFSM template, and passes verification.

        Parameters
        ----------
        line : str
            Input line of text to be parsed.
        count : int
            Count argument passed to `CategoryLinePattern`.
        expected_template_snippet : str
            The expected template snippet generated from the input line.
        expected_textfsm_template : str
            The expected normalized TextFSM template.
        expected_result : list[dict]
            The expected parsed result when verifying the template snippet.
        """
        # --- Action ---
        node = CategoryLinePattern(line, count=count)
        generated_snippet = node.to_template_snippet()

        # --- Assertions ---
        # Snippet matches expected
        assert generated_snippet == expected_template_snippet, (
            f"Generated snippet {generated_snippet!r} does not match expected {expected_template_snippet!r}"
        )

        # Generate TextFSM template from snippet
        raw_textfsm_template = get_textfsm_template(generated_snippet)

        # Normalize template by replacing actual dates with placeholder
        normalized_textfsm_template = replace_dates_with_placeholder(
            raw_textfsm_template)

        # Template matches expected
        assert normalized_textfsm_template == expected_textfsm_template, (
            "Normalized TextFSM template does not match expected template"
        )

        # Verification passes
        is_verified = verify(generated_snippet, line, expected_result=expected_result)
        assert is_verified, "Verification failed: parsed result did not match expected"
