import re

import pytest           # noqa
from textwrap import dedent

from textfsmgen.core import get_textfsm_template
from textfsmgen.core import verify

from textfsmgen.gpcategory import CategoryLinesPattern


class TestCategoryLinesPattern:
    """Test class for CategoryLinesPattern"""
    def test_to_starting_from_and_ending_to_arguments(self):

        test_data = dedent("""
            line 1: blab blab
            line 2: 123 blab
            fruits: orange, peach
            meat: pork
            drinks: water
            line k: 1.12 blab
            other fruits: mango
            other meat: chicken
            other drinks: pepsi
            """).strip()

        expected_template_snippet = dedent(r"""
            line 2: digits() blab -> Table
            Table
            fruits: mixed_phrase(var_fruits)
            meat: letters(var_meat)
            drinks: letters(var_drinks)
            line k: number() blab -> EOF            
        """).strip()

        expected_template = dedent(r"""
            ################################################################################
            # Template is generated by TextFSM Generator Community Edition
            # Created date: YYYY-mm-dd
            ################################################################################
            Value fruits ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*( [\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)
            Value meat ([a-zA-Z]+)
            Value drinks ([a-zA-Z]+)
            
            Start
              ^line 2: \d+ blab -> Table
            
            Table
              ^fruits: ${fruits}
              ^meat: ${meat}
              ^drinks: ${drinks}
              ^line k: \d*[.]?\d+ blab -> EOF
        """).strip()

        expected_result = [{'fruits': 'orange, peach', 'meat': 'pork', 'drinks': 'water'}]

        node = CategoryLinesPattern(test_data, starting_from=1, ending_to=5)
        tmpl_snippet = node.to_template_snippet()
        assert tmpl_snippet == expected_template_snippet

        template = get_textfsm_template(tmpl_snippet)
        template = re.sub(r'\d{4}-\d\d-\d\d', 'YYYY-mm-dd', template)
        assert template == expected_template

        is_verified = verify(tmpl_snippet, test_data,
                             expected_result=expected_result)
        assert is_verified
