"""
Unit tests for the `textfsmgen.gpcategory.CategoryLineTranslator` class.

Usage
-----
Run pytest in the project root to execute these tests:
    $ pytest tests/integration/category_form/test_starting_from_ending_at_param.py
    or
    $ python -m pytest tests/integration/category_form/test_starting_from_ending_at_param.py
"""

from textfsmgen.core.template import get_textfsm_template
from textfsmgen.core.verify import verify_textfsm

from textfsmgen.engine.category import CategoryLinesTranslator

from tests.unit import replace_dates_with_placeholder

from textfsmgen.libs.decorators import normalize_output


@normalize_output
def get_test_data():
    return """
        line 1: blab blab
        line 2: 123 blab
        fruits: orange, peach
        meat: pork
        drinks: water
        line k: 1.12 blab
        other fruits: mango
        other meat: chicken
        other drinks: pepsi
        """


@normalize_output
def get_expected_snippet():
    return r"""
        line 2: digits() blab -> Table
        Table
        fruits: mixed_word_group(var_fruits)
        meat: word(var_meat)
        drinks: word(var_drinks)
        line k: number() blab -> EOF            
    """


@normalize_output
def get_expected_template():
    """
    Returns the expected full TextFSM template with normalized date
    placeholder (``YYYY-mm-dd``)
    """
    return r"""
        ################################################################################
        # Template is generated by TextFSMGen CE
        # Created date: YYYY-mm-dd
        ################################################################################
        Value fruits ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*(\s+[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)
        Value meat ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)
        Value drinks ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)

        Start
          ^line 2: \d+ blab -> Table

        Table
          ^fruits: ${fruits}
          ^meat: ${meat}
          ^drinks: ${drinks}
          ^line k: \d*[.]?\d+ blab -> EOF
    """


def get_expected_result():
    return [{"fruits": "orange, peach", "meat": "pork", "drinks": "water"}]


def test():

    test_data = get_test_data()
    exp_snippet = get_expected_snippet()
    exp_template = get_expected_template()
    exp_result = get_expected_result()

    # --- Action ---
    node = CategoryLinesTranslator(test_data, starting_from=1, ending_at=5)
    generated_snippet = node.to_template_snippet()

    # --- Assertions ---
    # Snippet matches expected

    assert generated_snippet == exp_snippet

    # TextFSM template matches expected (normalize dates first)

    # Generate TextFSM template from snippet
    raw_template = get_textfsm_template(generated_snippet)

    # Normalize template by replacing actual dates with placeholder
    normalized_template = replace_dates_with_placeholder(raw_template)

    # Compare against expected template
    assert normalized_template == exp_template

    # Verification passes

    # is_verified = verify_snippet(
    #     generated_snippet, test_data, expected_result=exp_result
    # )
    # assert is_verified
