"""
Unit tests for the `textfsmgen.engine.category.CategoryLineTranslator` class.

Usage
-----
Run pytest in the project root to execute these tests:
    $ pytest tests/integration/category_form/test_lines_to_template.py
    or
    $ python -m pytest tests/integration/category_form/test_lines_to_template.py
"""

from textfsmgen.core.template import get_textfsm_template
from textfsmgen.core.verify import verify_snippet

from textfsmgen.engine.category import CategoryLinesTranslator

from tests.unit import replace_dates_with_placeholder

from textfsmgen.libs.decorators import normalize_output


@normalize_output
def get_test_data():
    return """
        fruits: orange, peach
        meat: pork
        drinks: water
        """


@normalize_output
def get_expected_snippet():
    return """
        fruits: mixed_word_group(var_fruits)
        meat: word(var_meat)
        drinks: word(var_drinks)
    """


@normalize_output
def get_expected_template():
    return r"""
        ################################################################################
        # Template is generated by TextFSMGen CE
        # Created date: YYYY-mm-dd
        ################################################################################
        Value fruits ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*(\s+[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)
        Value meat ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)
        Value drinks ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)

        Start
          ^fruits: ${fruits}
          ^meat: ${meat}
          ^drinks: ${drinks}
    """


def get_expected_result():  # noqa
    return [{"fruits": "orange, peach", "meat": "pork", "drinks": "water"}]


def test():
    test_data = get_test_data()
    exp_snippet = get_expected_snippet()
    exp_template = get_expected_template()
    exp_result = get_expected_result()

    # --- Action ---
    node = CategoryLinesTranslator(test_data)
    tmpl_snippet = node.to_template_snippet()

    # --- Assertions ---
    # Snippet matches expected
    assert tmpl_snippet == exp_snippet, (
        f"Generated snippet {tmpl_snippet!r} does not match expected {exp_snippet!r}"
    )

    # Generate TextFSM template from snippet
    raw_textfsm_template = get_textfsm_template(tmpl_snippet)

    # Normalize template by replacing actual dates with placeholder
    normalized_textfsm_template = replace_dates_with_placeholder(raw_textfsm_template)

    # Template matches expected
    assert normalized_textfsm_template == exp_template, (
        "Normalized TextFSM template does not match expected template"
    )

    # Verification passes
    is_verified = verify_snippet(tmpl_snippet, test_data, expected_result=exp_result)
    assert is_verified, "Verification failed: parsed result did not match expected"
