"""
Unit tests for the `textfsmgen.engine.category.CategoryLineTranslator` class.

Usage
-----
Run pytest in the project root to execute these tests:
    $ pytest tests/unit/engine/category/test_line_to_template.py
    or
    $ python -m pytest tests/unit/engine/category/test_line_to_template.py
"""


import re

import pytest

from textfsmgen.core.verify import verify
from textfsmgen.core.template import get_textfsm_template

from textfsmgen.engine.category import CategoryLineTranslator
from textfsmgen.engine.category import VAR_REGISTRY

from tests.unit import replace_dates_with_placeholder

from textfsmgen.libs.common import dedent_and_strip


@pytest.mark.parametrize(
    "line, count, exp_snippet, exp_template, exp_result",
    [
        (
            'fruits:  orange, peach',
            1,
            r'fruits:  mixed_word_group(var_fruits)',
            dedent_and_strip(r"""
                ################################################################################
                # Template is generated by TextFSMGen CE
                # Created date: YYYY-mm-dd
                ################################################################################
                Value fruits ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*(\s+[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)

                Start
                  ^fruits: +${fruits}
            """),
            [{'fruits': 'orange, peach'}]
        ),
        (
            'total fruit(s): orange, peach',
            1,
            r'total fruit(s): mixed_word_group(var_total_fruit_s)',
            dedent_and_strip(r"""
                ################################################################################
                # Template is generated by TextFSMGen CE
                # Created date: YYYY-mm-dd
                ################################################################################
                Value total_fruit_s ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*(\s+[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)

                Start
                  ^total fruit\(s\): ${total_fruit_s}
            """),
            [{'total_fruit_s': 'orange, peach'}]
        ),
        (
            '  fruit(s): orange   meat: pork  drinks: water',
            3,
            r'  fruit(s): word(var_fruit_s)  meat: word(var_meat)  drinks: word(var_drinks)',
            dedent_and_strip(r"""
                ################################################################################
                # Template is generated by TextFSMGen CE
                # Created date: YYYY-mm-dd
                ################################################################################
                Value fruit_s ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)
                Value meat ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)
                Value drinks ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)

                Start
                  ^ +fruit\(s\): ${fruit_s} +meat: ${meat} +drinks: ${drinks}
            """),
            [{'fruit_s': 'orange', 'meat': 'pork', 'drinks': 'water'}]
        ),
        (
            'fruits:   meat: ',
            2,
            r'fruits:optional_spaces()anything(var_fruits, or_empty)  meat:optional_spaces()anything(var_meat, or_empty)',  # noqa
            dedent_and_strip(r"""
                ################################################################################
                # Template is generated by TextFSMGen CE
                # Created date: YYYY-mm-dd
                ################################################################################
                Value fruits ((.*|))
                Value meat ((.*|))

                Start
                  ^fruits: *${fruits} +meat: *${meat}
            """),
            [{'fruits': '', 'meat': ''}]
        ),
        (
            'fruits: orange   meat:  drinks: water',
            3,
            r'fruits: word(var_fruits)  meat:optional_spaces()anything(var_meat, or_empty)  drinks: word(var_drinks)',    # noqa
            dedent_and_strip(r"""
                ################################################################################
                # Template is generated by TextFSMGen CE
                # Created date: YYYY-mm-dd
                ################################################################################
                Value fruits ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)
                Value meat ((.*|))
                Value drinks ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)

                Start
                  ^fruits: ${fruits} +meat: *${meat} +drinks: ${drinks}
            """),
            [{'fruits': 'orange', 'meat': '', 'drinks': 'water'}]
        ),
        (
            'fruits:   meat:  drinks: water',
            3,
            r'fruits:optional_spaces()anything(var_fruits, or_empty)  meat:optional_spaces()anything(var_meat, or_empty)  drinks: word(var_drinks)',     # noqa
            dedent_and_strip(r"""
                ################################################################################
                # Template is generated by TextFSMGen CE
                # Created date: YYYY-mm-dd
                ################################################################################
                Value fruits ((.*|))
                Value meat ((.*|))
                Value drinks ([a-zA-Z0-9_]*[a-zA-Z][a-zA-Z0-9_]*)

                Start
                  ^fruits: *${fruits} +meat: *${meat} +drinks: ${drinks}
            """),
            [{'fruits': '', 'meat': '', 'drinks': 'water'}]
        ),
        (
            'time: 08:30:00 P.M.',
            1,
            r'time: mixed_word_group(var_time)',
            dedent_and_strip(r"""
                ################################################################################
                # Template is generated by TextFSMGen CE
                # Created date: YYYY-mm-dd
                ################################################################################
                Value time ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*(\s+[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)

                Start
                  ^time: ${time}
            """),
            [{'time': '08:30:00 P.M.'}]
        ),
        (
            'time: 08:30:00 P.M.   mac_addr: 11:22:33:44:55:66',
            2,
            r'time: mixed_word_group(var_time)  mac_addr: mixed_number(var_mac_addr)',
            dedent_and_strip(r"""
                ################################################################################
                # Template is generated by TextFSMGen CE
                # Created date: YYYY-mm-dd
                ################################################################################
                Value time ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*(\s+[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)
                Value mac_addr ([+\(\[\$-]?(\d+([,:/-]\d+)*)?[.]?\d+[\]\)%a-zA-Z]*)

                Start
                  ^time: ${time} +mac_addr: ${mac_addr}
            """),
            [{'time': '08:30:00 P.M.', 'mac_addr': '11:22:33:44:55:66'}]
        ),
        (
            'time: 08:30:00 P.M.   ipv6: ::1234, 2000::ab, 2000::   mac_addr: 11:22:33:44:55:66',
            3,
            r'time: mixed_word_group(var_time)  ipv6: mixed_word_group(var_ipv6)  mac_addr: mixed_number(var_mac_addr)',
            dedent_and_strip(r"""
                ################################################################################
                # Template is generated by TextFSMGen CE
                # Created date: YYYY-mm-dd
                ################################################################################
                Value time ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*(\s+[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)
                Value ipv6 ([\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*(\s+[\x21-\x7e]*[a-zA-Z0-9][\x21-\x7e]*)+)
                Value mac_addr ([+\(\[\$-]?(\d+([,:/-]\d+)*)?[.]?\d+[\]\)%a-zA-Z]*)

                Start
                  ^time: ${time} +ipv6: ${ipv6} +mac_addr: ${mac_addr}
            """),
            [{'time': '08:30:00 P.M.', 'ipv6': '::1234, 2000::ab, 2000::', 'mac_addr': '11:22:33:44:55:66'}]
        ),
    ]
)
def test(line, count, exp_snippet, exp_template, exp_result):
    """
    Verify that `CategoryLineTranslator.to_template_snippet` generates the expected
    snippet, produces a valid TextFSM template, and passes verification.
    """
    # --- Action ---
    VAR_REGISTRY.reset()
    node = CategoryLineTranslator(line, count=count)
    generated_snippet = node.to_snippet()
    # --- Assertions ---
    # Snippet matches expected
    assert generated_snippet == exp_snippet, (
        f"Generated snippet {generated_snippet!r} does not match expected {exp_snippet!r}"
    )

    # Generate TextFSM template from snippet
    raw_textfsm_template = get_textfsm_template(generated_snippet)

    # Normalize template by replacing actual dates with placeholder
    normalized_textfsm_template = replace_dates_with_placeholder(raw_textfsm_template)

    # Template matches expected
    assert normalized_textfsm_template == exp_template, (
        "Normalized TextFSM template does not match expected template"
    )

    # Verification passes
    is_verified = verify(generated_snippet, line, expected_result=exp_result)
    assert is_verified, "Verification failed: parsed result did not match expected"
